# This is a basic workflow to help you get started with Actions
 
name: On Push - Generazione report complessivo (xls) di tutte le versioni.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: envForGithubActions
    
       
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
     
             
      - name: Step 3 - Unzip ed esecuzione progetto unisciReportExcel
        run: |
          echo "Proviamo ad unzippare"
          unzip unisciReportExcel
          echo "Unzippato"
          ls -a
          cd unisciReportExcel/target
          echo "Vediamo contenuto cartella target"
          ls -a
          sudo bash -c 'java -jar unisciReportExcel-0.0.1-jarReportTest.jar /home/runner/work/Tesi-ReportFinali-StrumentoGenerale/Tesi-ReportFinali-StrumentoGenerale/Report-Separati reportComplessivo'
          
      - name: Step 4 - Sposta file xls generati
        run: |
          ls -a
          cd unisciReportExcel/target
          echo "Vediamo contenuto cartella target"
          ls -a     
          sudo cp reportComplessivo.xls /home/runner/work/Tesi-ReportFinali-StrumentoGenerale/Tesi-ReportFinali-StrumentoGenerale 
          
      - name: Step 5 - Push dei file dei report ottenuti
        run: |
          echo "Vediamo quali cartelle ci sono nella directory di partenza"
          ls -a
          git status
          git config --global user.email "${{ secrets.EMAIL_ACCOUNT_GITHUB }}"
          git config --global user.name "${{ secrets.NOME_ACCOUNT_GITHUB }}"
          git config --global user.password "${{ secrets.PASSWORD_ACCOUNT_GITHUB }}"
          echo "Andiamo ad aggiungere i file xls"
          git add *.xls
          echo "File xls aggiunti!"
          echo "`date +%Y-%m-%d_%H-%M-%S`" > timeCommit.txt
          git add timeCommit.txt
          git commit -m "Aggiunta dei report complessivi finali"
          git branch -M master 
          git push -u origin master
          
          
